server:
  port: 18080

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:13300/realms/my-realm}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**, /internal/users/**, /api/couriers/**, /internal/couriers/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/orders/**

            - id: hub-service
              uri: lb://HUB-SERVICE
              predicates:
                - Path=/api/hubs/**

            - id: hub-inventory-service
              uri: lb://HUB-SERVICE
              predicates:
                - Path=/api/hub-inventories/**, /internal/hub-inventories/**

            - id: hub-route-service
              uri: lb://ROUTE-SERVICE
              predicates:
                - Path=/api/hub-routes/**

            - id: company-service
              uri: lb://COMPANY-SERVICE
              predicates:
                - Path=/api/companies/**

            - id: item-service
              uri: lb://ITEM-SERVICE
              predicates:
                - Path=/api/items/**

            - id: delivery-service
              uri: lb://DELIVERY-SERVICE
              predicates:
                - Path=/api/deliveries/**

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:18761/eureka/}

keycloak:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
